language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - python3 setup.py install
  - coverage run --source=VirtualJudgeSpider setup.py test
after_success:
  coveralls